### PR TITLE
Incremental refactoring

### PR DESCRIPTION
**Pull request by codingo**
This PR removes a number redundant code blocks and reorganises for readability.

### CODE REVIEW

**Comment by UltimateHackers** [comment]
I got this error when I entered a hash:
```
Enter your hash: d033e22ae348aeb5660fc2140aec35850c4da997 
[!] Hash function : SHA1
Traceback (most recent call last):
  File "hash.py", line 95, in <module>
    main()
  File "hash.py", line 89, in main
    beta()
  File "hash.py", line 42, in beta
    data = urlencode({"auth":"8272hgt", "hash":hashvalue, "string":"","Submit":"Submit"})
NameError: global name 'hashvalue' is not defined
```
Please fix it so I can merge.

**Comment by codingo** [comment]
It may be a couple of days until I can look at this again, just touching base to let you know I'm not ignoring this!

**Comment by UltimateHackers** [comment]
Ah thanks.

**Comment by UltimateHackers** [comment]
Can I close it now?

**Pull request closed without merging**
